name: Scheduled Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user
        echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV

    - name: Verify AWS CLI Installation
      run: aws --version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Create RDS Snapshot
      run: |
        INSTANCE_ID="bluecross-db"
        SNAPSHOT_ID="${INSTANCE_ID}-snapshot-$(date +%Y%m%d%H%M%S)"
        aws rds create-db-snapshot --db-instance-identifier $INSTANCE_ID --db-snapshot-identifier $SNAPSHOT_ID --region ap-south-1

